HOST_URL: "https://matrix-client.matrix.org"
CLIENT_ID: "@noamtamir:matrix.org"
PASSWORD: "4Z9D#jCa9mzBZhQ"
ACCESS_TOKEN: "MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI4Y2lkIHVzZXJfaWQgPSBAbm9hbXRhbWlyOm1hdHJpeC5vcmcKMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSBPbGZFWjgjLi5xclVURGp2CjAwMmZzaWduYXR1cmUg7MbhznbybE0hC0D083Yk7PM4j_BBxmOsFfTYAKgoTg8K"
MAIN_ROOM_ID: "!TqkAvjdrufUnAtsYwk:yoavmoshe.com"

PLAYERS:
  noam:
    user_id: '@noamtamir:matrix.org'
    room_id: ''
  yuval:
    user_id: '@whatsapp_972546685339:yoavmoshe.com'
    room_id: ''
  yoav:
    user_id: '@chat:yoavmoshe.com'
    room_id: ''
  alon:
    user_id: '@whatsapp_972546685339:yoavmoshe.com'
    room_id: ''
  ohad:
    user_id: '@whatsapp_972546685339:yoavmoshe.com'
    room_id: ''
  ido:
    user_id: '@whatsapp_972546685339:yoavmoshe.com'
    room_id: ''
  elad:
    user_id: '@whatsapp_972546685339:yoavmoshe.com'
    room_id: ''