HOST_URL: '' # 'https://matrix-client.matrix.org'
CLIENT_ID: '' # '@noamtamir:matrix.org'
PASSWORD: ''
ACCESS_TOKEN: '' # can be found in element in Settings -> Help & About -> Advanced -> Acces Token
MAIN_ROOM_ID: '' # can be found in room Settings -> Advanced -> Room Information -> Internal room ID
                 # (will look something like '!xxxxxxxxxxxxxxxxx:matrix.org')
SCHEDULE:
  VOTE1: '20:00'
  VOTE2: '20:30'
  END_DAY: '21:00'
  BEGIN_DAY: '9:30'

PLAYERS:
  player1:
    user_id: '' # '@player1:matrix.org'
    room_id: '' # '!xxxxxxxxxxxxxxxxx:matrix.org'
  player2:
    user_id: '' # '@player2:matrix.org'
    room_id: '' # '!xxxxxxxxxxxxxxxxx:matrix.org'
  player3:
    user_id: '' # '@player3:matrix.org'
    room_id: '' # '!xxxxxxxxxxxxxxxxx:matrix.org'

#TODO: You need to set up the Main Room in advance, as well as a room with each player. All rooms should be unencrypted.